import re
new_file=input('input a filename as the new fasta file: ')
if re.search(r'.fa$',new_file): #confirm the new file is in fasta format
	file=open('Saccharomyces_cerevisiae.R64-1-1.cdna.all.fa')
	output=open(f'{new_file}','w')
	se = file.read()
	se = ''.join(se.split('\n'))
	se=se.lstrip('>')
	gene=re.split(r'>',se)
	result=''
	for i in range(len(gene)):
		if re.search(r'GAATTC',gene[i]):
			a=str(re.findall(r'gene:(.+?)\s',gene[i]))
			a=a.strip("['']")
			b=str(re.findall(r'](.+)',gene[i]))
			b=b.strip("['']")
			sequence_cut=b.count('GAATTC')
			number=b.count('GAATTC')+1
			result=result+'>'+a+'\n'+'The number of gene sequence that can be cut by EcoRI:'+str(sequence_cut)+'\n'+'The number of fragments which could be generated by EcoRI:'+str(number)+'\n'+'Sequence:'+b+'\n'
	result=result[:-1]
	output.write(result)
	file.close()
	output.close()